swagger: "2.0"
info:
  description: "Example of API"
  version: "0.0.1"
  title: "API Boilerplate"
  contact:
    email: "developer@mail.io"
host: "petstore.swagger.io"
basePath: "/api/v1"
tags:
- name: "Examples of handlers"
  description: "Everything about our API"
schemes:
- "https"
paths:
  /get:
    post:
      tags:
      - "API"
      summary: "get users"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            items:
              $ref: "#/definitions/Users"
  /set:
    post:
      tags:
      - "API"
      summary: "set new user"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            items:
              $ref: "#/definitions/SimpleResponse"
definitions:
  SimpleResponse:
    type: "object"
    properties:
      success:
        type: "boolean"
      error:
        type: "string"
  Users:
    type: "object"
    properties:
      success:
        type: "array"
        items:
          $ref: "#/definitions/User"
      error:
        type: "string"
  User:
    type: "object"
    required:
    - "id"
    - "name"
    - "profession"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      profession:
        type: "string"
