version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: system/Dockerfile
    restart: always
    ports:
      - "5000:5000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: flask_api_boilerplate